-- Add 6 New Plugins to the Plugin Store
-- Plugins: Preen PSU, Keysight DAQ, Kwikwai K110, GRL PD, Sifos PoE, Time Machines Grandmaster

INSERT INTO public.plugins (
    name,
    slug,
    display_name,
    short_description,
    full_description,
    category,
    principle,
    tags,
    current_version,
    base_price,
    currency,
    pricing_model,
    monthly_price,
    has_free_trial,
    trial_duration_days,
    trial_requires_payment,
    features,
    is_published,
    is_featured,
    is_active,
    publisher_name,
    publisher_email,
    total_downloads,
    average_rating,
    total_reviews
) VALUES
(
    'Preen PSU',
    'preen-psu',
    'Preen PSU',
    'Preen programmable power supply control',
    'Control and monitor Preen programmable power supplies with automated test sequences and real-time voltage/current logging.',
    'power',
    'electrical',
    '["power supply", "preen", "voltage", "current", "automation", "testing"]'::jsonb,
    '1.0.0',
    49.00,
    'USD',
    'subscription_monthly',
    49.00,
    true,
    30,
    true,
    '["Real-time voltage and current monitoring", "Automated test sequences", "Multi-channel power supply control", "Data logging and export", "Custom power profiles", "Safety limits and protection"]'::jsonb,
    true,
    false,
    true,
    'Lyceum Audio Labs',
    'support@lyceum.com',
    0,
    0.00,
    0
),
(
    'Keysight DAQ',
    'keysight-daq',
    'Keysight DAQ',
    'Data acquisition from Keysight instruments',
    'Direct integration with Keysight data acquisition systems for seamless measurement capture and real-time data streaming.',
    'data-acquisition',
    'measurement',
    '["keysight", "daq", "data acquisition", "measurement", "streaming", "multi-channel"]'::jsonb,
    '1.0.0',
    49.00,
    'USD',
    'subscription_monthly',
    49.00,
    true,
    30,
    true,
    '["Multi-channel data acquisition", "Real-time streaming", "High sample rate support", "Triggered measurements", "Data export to multiple formats", "Integration with Lyceum analytics"]'::jsonb,
    true,
    false,
    true,
    'Lyceum Audio Labs',
    'support@lyceum.com',
    0,
    0.00,
    0
),
(
    'Kwikwai K110',
    'kwikwai-k110',
    'Kwikwai K110',
    'HDMI test and measurement integration',
    'Full integration with Kwikwai K110 HDMI analyzer for comprehensive video signal testing and compliance verification.',
    'video',
    'hdmi',
    '["kwikwai", "hdmi", "video", "compliance", "testing", "4k", "8k"]'::jsonb,
    '1.0.0',
    49.00,
    'USD',
    'subscription_monthly',
    49.00,
    true,
    30,
    true,
    '["HDMI signal analysis", "Compliance testing suites", "4K/8K resolution support", "EDID management", "HDCP verification", "Automated test reports"]'::jsonb,
    true,
    false,
    true,
    'Lyceum Audio Labs',
    'support@lyceum.com',
    0,
    0.00,
    0
),
(
    'GRL PD',
    'granite-river-labs-pd',
    'GRL PD',
    'USB Power Delivery compliance testing',
    'USB-PD compliance testing integration with Granite River Labs analyzers for complete power delivery validation.',
    'power-delivery',
    'usb',
    '["grl", "usb-pd", "power delivery", "compliance", "certification", "usb-c"]'::jsonb,
    '1.0.0',
    49.00,
    'USD',
    'subscription_monthly',
    49.00,
    true,
    30,
    true,
    '["USB-PD 2.0/3.0/3.1 testing", "EPR specification support", "Compliance test automation", "Certification-ready reports", "Protocol analysis", "Power profile testing"]'::jsonb,
    true,
    false,
    true,
    'Lyceum Audio Labs',
    'support@lyceum.com',
    0,
    0.00,
    0
),
(
    'Sifos PoE',
    'sifos-poe',
    'Sifos PoE',
    'Power over Ethernet test automation',
    'Automate PoE testing with Sifos analyzers including compliance testing, power measurements, and protocol analysis.',
    'networking',
    'poe',
    '["sifos", "poe", "power over ethernet", "802.3af", "802.3at", "802.3bt", "compliance"]'::jsonb,
    '1.0.0',
    49.00,
    'USD',
    'subscription_monthly',
    49.00,
    true,
    30,
    true,
    '["802.3af/at/bt compliance testing", "PSE and PD testing", "Power measurement and logging", "Protocol analysis", "Automated test sequences", "Multi-port testing support"]'::jsonb,
    true,
    false,
    true,
    'Lyceum Audio Labs',
    'support@lyceum.com',
    0,
    0.00,
    0
),
(
    'Time Machines Grandmaster',
    'time-machines-grandmaster',
    'Time Machines Grandmaster',
    'Precision timing and synchronization',
    'GPS-synchronized precision timing integration with Time Machines Grandmaster for accurate timestamping and sync testing.',
    'timing',
    'synchronization',
    '["time machines", "grandmaster", "ptp", "ntp", "gps", "timing", "synchronization"]'::jsonb,
    '1.0.0',
    49.00,
    'USD',
    'subscription_monthly',
    49.00,
    true,
    30,
    true,
    '["GPS-synchronized timing", "PTP grandmaster support", "NTP integration", "Nanosecond accuracy", "Multi-domain support", "Timing event logging"]'::jsonb,
    true,
    false,
    true,
    'Lyceum Audio Labs',
    'support@lyceum.com',
    0,
    0.00,
    0
)
ON CONFLICT (slug) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    short_description = EXCLUDED.short_description,
    full_description = EXCLUDED.full_description,
    category = EXCLUDED.category,
    principle = EXCLUDED.principle,
    tags = EXCLUDED.tags,
    current_version = EXCLUDED.current_version,
    base_price = EXCLUDED.base_price,
    currency = EXCLUDED.currency,
    pricing_model = EXCLUDED.pricing_model,
    monthly_price = EXCLUDED.monthly_price,
    has_free_trial = EXCLUDED.has_free_trial,
    trial_duration_days = EXCLUDED.trial_duration_days,
    trial_requires_payment = EXCLUDED.trial_requires_payment,
    features = EXCLUDED.features,
    is_published = EXCLUDED.is_published,
    is_active = EXCLUDED.is_active,
    publisher_name = EXCLUDED.publisher_name,
    publisher_email = EXCLUDED.publisher_email,
    updated_at = NOW();
